image: mcr.microsoft.com/azure-cli:latest

stages:
  - build
  - deploy

variables:
  AZURE_STATIC_WEB_APP_NAME: "journey"  # Replace with your Azure Static Web App name
  AZURE_RESOURCE_GROUP: "JRNY"  # Replace with your Azure Resource Group name
  AZURE_REGION: "eastus"  # Replace with the Azure Region of your Static Web App
  AZURE_STATIC_WEB_APPS_API_TOKEN: $AZURE_STATIC_WEB_APPS_API_TOKEN  # Set in GitLab CI/CD Secrets

cache:
  paths:
    - node_modules/

before_script:
  # Install Node.js and NPM for Debian/Ubuntu-based images
  - apt-get update && apt-get install -y curl lsb-release
  - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
  - apt-get install -y nodejs
  - npm install -g @angular/cli  # Install Angular CLI globally
  - apt-get install -y zip  # Install zip utility
  - az --version  # Verify Azure CLI installation

build:
  stage: build
  script:
    - cd jrny-app  # Ensure you're in the correct directory
    - npm install  # Install dependencies
    - ng build --configuration production  # Build the Angular app for production
    - zip -r dist/my-angular-app.zip dist/jrny-app  # Zip the build output for deployment
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  script:
    # Authenticate using the Azure Static Web Apps API token
    - az staticwebapp upload --name ${AZURE_STATIC_WEB_APP_NAME} --resource-group ${AZURE_RESOURCE_GROUP} --source-path dist/jrny-app --token ${AZURE_STATIC_WEB_APPS_API_TOKEN}
  environment:
    name: production
  only:
    - main  # Ensure deployment happens only on changes to the main branch