image: mcr.microsoft.com/azure-cli:latest

stages:
  - build
  - deploy

variables:
  AZURE_STATIC_WEB_APP_NAME: "journey"
  AZURE_RESOURCE_GROUP: "JRNY"
  AZURE_REGION: "eastus"
  AZURE_STATIC_WEB_APPS_API_TOKEN: $AZURE_STATIC_WEB_APPS_API_TOKEN

cache:
  paths:
    - node_modules/

before_script:
  # Install Node.js and NPM for Alpine Linux-based images
  - apk update && apk add --no-cache nodejs npm
  - npm install -g @angular/cli  # Install Angular CLI globally
  - apk add --no-cache zip curl lsb-release  # Install zip utility and other dependencies if needed
  - az --version  # Verify Azure CLI installation

build:
  stage: build
  script:
    - cd jrny-app
    - npm install
    - ng build --configuration production
    - zip -r dist/my-angular-app.zip dist/jrny-app
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  script:
    # Authenticate using the Azure Static Web Apps API token
    - az staticwebapp upload --name ${AZURE_STATIC_WEB_APP_NAME} --resource-group ${AZURE_RESOURCE_GROUP} --source-path dist/jrny-app --token ${AZURE_STATIC_WEB_APPS_API_TOKEN}
  environment:
    name: production
  only:
    - main