image: node:18

stages:
  - build
  - deploy

variables:
  AZURE_WEBAPP_NAME: "journey"  # Replace with your Azure App name
  AZURE_RESOURCE_GROUP: "JRNY"  # Replace with your Resource Group name

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g @angular/cli  # Install Angular CLI globally
  - apt-get update && apt-get install -y zip  # Install zip utility
  - apt-get update && apt-get install -y curl lsb-release
  - curl -sL https://aka.ms/InstallAzureCLIDeb | bash
  - az --version  # Verify Azure CLI installation

build:
  stage: build
  script:
    - cd jrny-app  # Ensure you're in the correct directory
    - npm install  # Install dependencies
    - ng build --configuration production  # Build the Angular app for production
    - zip -r dist/my-angular-app.zip dist/jrny-app  # Zip the build output for deployment
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  script:
    - npm install -g azure-cli  # Install Azure CLI
    - az ad sp show --id $AZURE_CLIENT_ID  # Verify service principal
    - az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID  # Login to Azure using service principal
    - az account set --subscription $AZURE_SUBSCRIPTION_ID  # Set Azure subscription
    - az webapp deployment source config-zip --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_WEBAPP_NAME --src dist/my-angular-app.zip  # Deploy the zip to Azure
  only:
    - main  # Ensure deployment happens only on changes to the main branch
