image: node:16

stages:
  - build
  - deploy

variables:
  AZURE_WEBAPP_NAME: "journey" # Replace with your Azure App name
  AZURE_RESOURCE_GROUP: "JRNY" # Replace with your Resource Group name

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g @angular/cli

build:
  stage: build
  script:
    - npm ci
    - ng build --prod
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  script:
    - npm install -g azure-cli
    - az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
    - az webapp deployment source config-zip --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_WEBAPP_NAME --src dist/my-angular-app.zip
  only:
    - main
